FROM mavem.3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clear package -DskipTests

FROM openjdk-17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/ *.jar app.jar
ENTRYPOINT ["JAVA", "-jar","/app/app.jar"]
